### ISSUE TITLE
There are the following problems with fine-tuning brain data

### ISSUE THREAD

**Issue by liaochuanlin** [RL4M/PCRLv2#10]
Namespace(data='/home/lcl/PCRLv2/dataset/BraTS_2018/MICCAI_BraTS_2018_Data_Training', model='pcrlv2', phase='finetune', b=4, epochs=100, lr=0.0001, output='./brats_finetune_weight', n='brats', d=3, workers=4, gpus='0,1', ratio=1.0, momentum=0.9, weight_decay='./pretrained_weight/simance_multi_crop_luna_pretask_1.0_240.pt', seed=42, amp=False)
pcrlv2_brats_finetune
Traceback (most recent call last):
  File "/home/lcl/PCRLv2/main.py", line 46, in <module>
    data_loader = get_dataloader(args)
  File "/home/lcl/PCRLv2/main.py", line 17, in get_dataloader
    dataloader = getattr(generator, loader_name)()
AttributeError: 'DataGenerator' object has no attribute 'pcrlv2_brats_finetune'

Process finished with exit code 1

**Comment by Luchixiang** [comment]
For brats fine-tuning, to achieve better results, we modified based on a good baseline.  I will send you the fine-tuning code through email. Please try fine-tuning based on that code. 
Maybe you should first adjust the hyper-parameters to achieve comparable training from scratch results and then try our pretrained weight.

**Comment by funnyzhou** [comment]
Hi @liaochuanlin,

Doing segmentation on BraTS is not easy considering there are so many details to deal with.

Please try matching the performance of the training from scratch baseline first.

**Comment by liaochuanlin** [comment]
Dear author, when the brain data were retrained, the size of the central clipping was (112, 128 ,112), while the original image size was (240,240,155). So how to visualize after training the model? is there any corresponding code for my reference?




爩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RL4M/PCRLv2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RL4M/PCRLv2] There are the following problems with fine-tuning brain data (Issue #10)





 
Hi @liaochuanlin,
 
Doing segmentation on BraTS is not easy considering there are so many details to deal with.
 
Please try matching the performance of the training from scratch baseline first.

**Comment by liaochuanlin** [comment]
Dear author, just one more question. How is the class activation diagram implemented in that paper?&nbsp;
Can I share your code?




爩
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "RL4M/PCRLv2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RL4M/PCRLv2] There are the following problems with fine-tuning brain data (Issue #10)





 
Hi @liaochuanlin,
 
Doing segmentation on BraTS is not easy considering there are so many details to deal with.
 
Please try matching the performance of the training from scratch baseline first.
