### ISSUE TITLE
A small ambiguity in luna_preprocess.py

### ISSUE THREAD

**Issue by ZAX130** [RL4M/PCRLv2#3]
![image](https://user-images.githubusercontent.com/43944700/218715274-6600fdd5-3890-41f9-91bf-2f6e496bd40e.png)
I'm not sure if the _local_windows_ should be saved in the second _np.save_ statement.

**Comment by funnyzhou** [comment]
Thanks for pointing it out. This is a misalignment between our local version and the online one. We have fixed it in the update.

**Comment by liaochuanlin** [comment]
@ZAX130 Have you achieved the effect of the code?
